### ISSUE TITLE
Collaborate on improving intl-messageformat?

### ISSUE THREAD

**Issue by ericf** [thetalecrafter/message-format#1]
I happened to come across your package and see that you're shooting for something similar to ours, [`intl-messageformat`](https://github.com/yahoo/intl-messageformat), it would be create to collaborate so we can address the original issues you had.

Based on your [comparison](https://github.com/thetalecrafter/message-format#comparison-to-intl-messageformat), it looks like your main issues are with the [parser](https://github.com/yahoo/intl-messageformat-parser). We already have an open issue for using single-quotes to escape: https://github.com/yahoo/intl-messageformat/issues/85

As for the parser's overall size and speed, we are of course open to making it smaller and faster, and it's core API is its AST format which we think is superior to other options we found before writing it.

Are you up for collaborating with us on improving the parser so there's a canonical parser? Also I'm curious what issues you had with our runtime?

**Comment by thetalecrafter** [comment]
I think that sounds great. Yeah, my only real issue was the parser. Mostly I rewrote the rest for my own education. :)

The AST is fine, except that # is a special character, and I would think the parser should generate a node for it, instead of trying to determine later if it is significant or was initially escaped. `pluralNumberElement` perhaps? I opted in message-format/parser for a format that serializes very small, since it is a non-public implementation detail, but if a standard AST is desirable I'm not opposed.

If you'd think it worthwhile, I could port my hand-rolled parser to generate the same AST initially as an alternative in intl-messageformat-parser. My rough benchmarks put my parser at ~20x the speed (on v8) of what peg generated. I don't believe generating a different AST would have much of an impact.

As for the runtime and compiler, I don't have any complaints. There may be some room to squeeze out more performance, but it's not nearly as dramatic as the parser.

**Comment by ericf** [comment]
Cool! The `pluralNumberElement` idea makes sense, and will make the compiler simpler as well.

The main thing PEG has going for it is readability and easy to extend, but it does produce a lot of code and can be slow. We found this tradeoff to be "oaky" since the usage is to parse once, `format()` many times, therefore we put more effort on the `format()` side of things.

We are going to start working on [adding `selectordinal` support](https://github.com/yahoo/intl-messageformat/issues/84#issuecomment-74315409), which will require an update to the parser. I will also look into adding the `pluralNumberElement` and escaping changes at that time. The good thing with the AST being the public API is that we can swap out PEG for a hand-rolled implementation like yours.

When we get PRs open for `selectordinal` and `pluralNumberElement` I can ping you in those PRs and we can start working towards these improvements to the parser.
